# Generated by Django 5.0.2 on 2024-03-01 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=10)),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('after_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('flat_change', models.DecimalField(decimal_places=2, max_digits=7)),
                ('percentage_change', models.DecimalField(decimal_places=2, max_digits=4)),
                ('changed', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.company')),
            ],
        ),
    ]
