# Generated by Django 5.0.2 on 2024-03-01 06:52

from django.core.management import call_command
from django.db import migrations


def populate_historic_data(apps, schema_editor):
    call_command('fill_historic_data')


class Migration(migrations.Migration):
    dependencies = [('app', '0002_initial_companies_data')]

    operations = [migrations.RunPython(populate_historic_data)]
